# mysql
spring:
   datasource:
    driver-class-name: org.postgresql.Driver
#    driver-class-name:  com.mysql.jdbc.Driver
    url: jdbc:postgresql://192.168.220.154:5432/escheduler
#    url: jdbc:mysql://192.168.220.188:3306/escheduler_new?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root@123
#    platform:
    continue-on-error: true


#mybatis
mybatis-plus:
  mapper-locations: classpath*:/cn.escheduler.dao.mapper/*.xml
  typeEnumsPackage: cn.escheduler.*.enums
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: cn.escheduler.dao.entity
  global-config:
    #数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: AUTO
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: NOT_NULL
      #驼峰下划线转换
      column-underline: true
      logic-delete-value: -1
      logic-not-delete-value: 0
    banner: false
  #原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'


# Logger Config
logging:
  level:
    cn.escheduler.dao: debug

