@startuml
'https://plantuml.com/activity-diagram-beta

start
:编译源代码
compilerRawScript();
:构建源代码绝对路劲名
buildJavaSourceCodeFileFullName();
:创建源代码文件
createJavaSourceFileIfNotExist();
:构建类路劲或模块路劲
buildResourcePath();
:构建编译命令
builder.toString();
:执行编译吗命令
shellCommandExecutor.run(compilerCommand.toString());
:删除源文件
Files.delete(Paths.get(fileName));
stop

@enduml
