@startyaml

JAVA_HOME8: "JAVA_HOME"
JAVA_HOME11: "JAVA_HOME8"
JAVA_HOME13: "JAVA_HOME11"
JAVA_HOME15: "JAVA_HOME13"
JAVA_HOME17: "JAVA_HOME17"
RUN_TYPE_JAVA: "JAVA"
RUN_TYPE_JAR: "JAR"
RUN_TYPE_JSHELL: "JSHELL"
PATH_SEPARATOR : "System.getProperty("path.separator")"
PATH_CURRENT_DIR: ".   <--（这是个英文句号）"
JAVA_SOURCE_CODE_NAME_TEMPLATE: "%s/java_%s.java"
@endyaml