@startuml
'https://plantuml.com/activity-diagram-beta

start
:构造实例 new JavaTask()
初始化实例 init()
进入业务逻辑 handle();

switch (判断RunType运行模式)
case (JAVA)
:开始构建JAR模式命令
buildJavaCommand();
:替换占位符${}为变量
buildJavaSourceContent();
:编译源代码
compilerRawScript();
:构建类路劲或模块路劲
buildResourcePath();
:构建JAVA运行模式命令
builder.toString();
case (JAR)
:开始构建JAR模式命令
buildJarCommand();
:构建类路劲或模块路劲
buildResourcePath();
:构建JAR运行模式命令
builder.toString();
endswitch
:选择JDK版本
buildJavaExecuteCommand();
switch (JavaVersion)
case (JAVA8)
  :JAVA_HOME8;
case (JAVA11)
  :JAVA_HOME11;
case (JAVA13)
  :JAVA_HOME13;
case (JAVA15)
  :JAVA_HOME15;
case (JAVA17)
  :JAVA_HOME17;
endswitch
:执行最终命令
shellCommandExecutor.run();

stop



@enduml
