@startuml
package "class org.apache.dolphinscheduler.plugin.task.api"{
    class TaskExecutionContext{
        many args...
    }
    abstract class AbstractCommandExecutor {
        # StringBuilder varPool
        - Process process
        # TaskExecutionContext taskRequest
        - void buildProcess(String)
        + TaskResponse run(String)
    }


    class ShellCommandExecutor extends AbstractCommandExecutor {
        - static final String SH = "sh";
        - static final String CMD = "cmd.exe";
    }

}
package "java.lang"{
    class ProcessBuilder
    {
        private List<String> command;
        private File directory;
        private Map<String,String> environment;
        private boolean redirectErrorStream;
        private Redirect[] redirects;
        directory(File file);
        redirectErrorStream(true);
        command(List<String> command);
        start();
    }
        AbstractCommandExecutor-->ProcessBuilder
}
package "org.apache.dolphinscheduler.plugin.task.java"{
    class JavaTask{
        -JavaParameters javaParameters;
        -ShellCommandExecutor shellCommandExecutor;
        -TaskExecutionContext taskRequest;
        +JavaTask(TaskExecutionContext taskRequest)
        + init()
        + void handle()
    }
    JavaTask*->ShellCommandExecutor
    JavaTask*->TaskExecutionContext
}


@enduml