{
 "title": "Master",
 "description": "Dashboard for Micrometer instrumented applications (Java, Spring Boot, Micronaut)",
 "time": { "from": "2023-03-07T04:20:35.626Z", "to": "2023-03-07T04:22:11.080Z" },
 "templating": {
  "list": [
   { "name": "application", "label": "Application", "query": { "query": "label_values(application)" } },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{application=\"$application\"}, instance)"
    }
   },
   {
    "name": "jvm_memory_pool_heap",
    "label": "JVM Memory Pools Heap",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"heap\"},id)"
    }
   },
   {
    "name": "jvm_memory_pool_nonheap",
    "label": "JVM Memory Pools Non-Heap",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"nonheap\"},id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "MasterServer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Master Overload/1m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "increase(ds_master_overload_count_total[1m])"
    }
   ]
  },
  {
   "title": "Master Consume Command/1m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "increase(ds_master_consume_command_count_total{}[1m])",
     "legendFormat": "master_consume_command"
    }
   ]
  },
  {
   "title": "JVM Thread",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "jvm_threads_live_threads{application=\"master-server\"}",
     "legendFormat": "live_thread"
    },
    {
     "expr": "jvm_threads_daemon_threads{application=\"master-server\"}",
     "legendFormat": "daemon_thread"
    },
    {
     "expr": "jvm_threads_peak_threads{application=\"master-server\"}",
     "legendFormat": "peak_thread"
    }
   ]
  },
  {
   "title": "Thread Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "jvm_threads_states_threads{application=\"master-server\"}"
    }
   ]
  },
  { "title": "Scheduler", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Job Total Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "JOBS" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ds_master_quartz_job_executed_total)"
    }
   ]
  },
  {
   "title": "Job Successful Rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ds_master_quartz_job_executed_total{result=\"success\"}) / sum(ds_master_quartz_job_executed_total) * 100"
    }
   ]
  },
  {
   "title": "Quartz Job Executed Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(ds_master_quartz_job_executed_total{})",
     "legendFormat": "Total"
    },
    {
     "expr": "ds_master_quartz_job_executed_total{result=\"success\"}",
     "legendFormat": "Successful"
    },
    {
     "expr": "ds_master_quartz_job_executed_total{result=\"failure\"}",
     "legendFormat": "Failed ({{exception}})"
    }
   ]
  },
  {
   "title": "Quartz Job Execution Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(ds_master_quartz_job_execution_time_seconds_sum[1m])/rate(ds_master_quartz_job_execution_time_seconds_count[1m])",
     "legendFormat": "avg ({{exception}})"
    },
    {
     "expr": "quartz_job_execution_seconds_max",
     "legendFormat": "max ({{exception}})"
    }
   ]
  },
  {
   "title": "Quartz Job Executed Count / Minute",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(ds_master_quartz_job_executed_total[1m]))",
     "legendFormat": "Total"
    },
    {
     "expr": "increase(ds_master_quartz_job_executed_total{result=\"success\"}[1m])",
     "legendFormat": "Successful"
    },
    {
     "expr": "increase(ds_master_quartz_job_executed_total{result=\"failure\"}[1m])",
     "legendFormat": "Failed ({{exception}})"
    }
   ]
  },
  {
   "title": "Quartz Job Execution Time Distribution",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 18 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(ds_master_quartz_job_execution_time_seconds_bucket[5m])) by (le))"
    }
   ]
  },
  { "title": "ProcessInstance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Process Instance State Count By Definition Code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "ds_workflow_instance_count_total{process_definition_code=\"dummy\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process Instance Submit/1m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "sum(increase(ds_workflow_instance_count_total{state=\"submit\"}[1m]))"
    }
   ]
  },
  {
   "title": "Process Instance Stop/1m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 6, "y": 36 },
   "targets": [
    {
     "expr": "sum(increase(ds_workflow_instance_count_total{state=\"stop\"}[1m]))"
    }
   ]
  },
  {
   "title": "Process Instance Finish/1m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 14, "y": 36 },
   "targets": [
    {
     "expr": "sum(increase(ds_workflow_instance_count_total{state=\"finish\"}[1m]))"
    }
   ]
  },
  {
   "title": "Process Instance Success /1m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "sum(increase(ds_workflow_instance_count_total{state=\"success\"}[1m]))"
    }
   ]
  },
  {
   "title": "Process Instance Timeout/1m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 44 },
   "targets": [
    {
     "expr": "sum(increase(ds_workflow_instance_count_total{state=\"timeout\"}[1m]))"
    }
   ]
  },
  {
   "title": "Process Instance Failure/1m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 44 },
   "targets": [
    {
     "expr": "sum(increase(ds_workflow_instance_count_total{state=\"fail\"}[1m]))"
    }
   ]
  },
  { "title": "Task", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Task Dispatch Count/1m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "sum(increase(ds_task_dispatch_count_total{}[1m]))"
    },
    {
     "expr": "sum(increase(ds_task_dispatch_failure_count_total{}[1m]))"
    },
    {
     "expr": "sum(increase(ds_task_dispatch_error_count_total{}[1m]))"
    }
   ]
  },
  {
   "title": "Task Submit Count/1m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 53 },
   "targets": [
    {
     "expr": "sum by(taskName)(increase(ds_task_instance_count_total{state=\"submit\"}[1m]))"
    }
   ]
  },
  {
   "title": "Task Finish Count/1m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 53 },
   "targets": [
    {
     "expr": "sum by(taskName)(increase(ds_task_instance_count_total{state=\"finish\"}[1m]))"
    }
   ]
  },
  {
   "title": "Task Success Count/1m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 61 },
   "targets": [
    {
     "expr": "sum by(taskName)(increase(ds_task_instance_count_total{state=\"success\"}[1m]))"
    }
   ]
  },
  {
   "title": "Task failure Count/1m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 61 },
   "targets": [
    {
     "expr": "sum by(taskName)(increase(ds_task_instance_count_total{state=\"fail\"}[1m]))"
    }
   ]
  },
  {
   "title": "Task Timeout Count/1m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 61 },
   "targets": [
    {
     "expr": "sum by(taskName)(increase(ds_task_instance_count_total{state=\"timeout\"}[1m]))"
    }
   ]
  },
  {
   "title": "Task Retry Count/1m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 69 },
   "targets": [
    {
     "expr": "sum by(taskName)(increase(ds_task_instance_count_total{state=\"retry\"}[1m]))"
    }
   ]
  },
  {
   "title": "Task Stop Count/1m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 69 },
   "targets": [
    {
     "expr": "sum by(taskName)(increase(ds_task_instance_count_total{state=\"retry\"}[1m]))"
    }
   ]
  },
  {
   "title": "Task Failover Count/1m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 69 },
   "targets": [
    {
     "expr": "sum by(taskName)(increase(ds_task_instance_count_total{state=\"failover\"}[1m]))"
    }
   ]
  }
 ]
}