{
 "title": "Worker",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Task Total Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(dolphinscheduler_task_execution_count_total)"
    }
   ]
  },
  {
   "title": "Task Successful Rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(dolphinscheduler_task_execution_count_total{result=\"success\"}) / sum(dolphinscheduler_task_execution_count_total) * 100"
    }
   ]
  },
  {
   "title": "Task Execution Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "millse" } },
   "yaxes": [
    { "format": "millse" }
   ],
   "targets": [
    {
     "expr": "rate(dolphinscheduler_task_execution_timer_seconds_sum[1m])/rate(dolphinscheduler_task_execution_timer_seconds_count[1m])",
     "legendFormat": "avg ({{exception}})"
    },
    {
     "expr": "dolphinscheduler_task_execution_timer_seconds_max",
     "legendFormat": "max ({{exception}})"
    }
   ]
  },
  {
   "title": "Task Execution Total/Success",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(dolphinscheduler_task_execution_count_total[1m]))",
     "legendFormat": "Total"
    },
    {
     "expr": "increase(dolphinscheduler_task_execution_count_total{result=\"success\"}[1m])",
     "legendFormat": "Successful"
    }
   ]
  },
  {
   "title": "Worker Submit Queue Full/1m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "increase(dolphinscheduler_worker_submit_queue_is_full_count_total{}[1m])"
    }
   ]
  },
  {
   "title": "Worker Overload Increase/1m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 8, "y": 16 },
   "targets": [
    {
     "expr": "increase(dolphinscheduler_worker_overload_count_total{}[1m])"
    }
   ]
  },
  {
   "title": "Worker Running Task",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 16 },
   "targets": [
    {
     "expr": "dolphinscheduler_worker_running_task_gauge{}"
    }
   ]
  },
  {
   "title": "Shell Task Execute/1d",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(increase(dolphinscheduler_task_execute_count_total{task_type=\"SHELL\"}[1d]))",
     "legendFormat": "SHELL"
    }
   ]
  },
  {
   "title": "Unkown Task Execution Total/1d",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 8, "y": 24 },
   "targets": [
    {
     "expr": "sum(increase(dolphinscheduler_task_execute_count_total{task_type=\"unknown\"}[1d]))"
    }
   ]
  },
  {
   "title": "Condition Task Execution Total/1d",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 24 },
   "targets": [
    {
     "expr": "sum(increase(dolphinscheduler_task_execute_count_total{task_type=\"CONDITIONS\"}[1d]))"
    }
   ]
  }
 ]
}