env:
  browser: true
  es6: true
  jquery: true
extends:
  - 'plugin:vue/essential'
  - standard
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
  PUBLIC_PATH: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
plugins:
  - vue
rules: {}
