syntax = "proto3";

package org.example.protobuf;

option java_package = "org.example.protobuf";
option java_multiple_files = true;
option java_outer_classname = "ProtoRepo";

// The greeting service definition.
service Greeter {
  // Sends a greeting. Original method.
  rpc SayHello (HelloRequest.H) returns (HelloReply) {}
  // Sends another greeting. New method.
  rpc SayHelloAgain (HelloRequest) returns (HelloReply) {}
}

// The request message containing the user's name.
message HelloRequest {
  // The name of the user.
  string username = 1;
  message H {
    string username = 3;
  }
}

enum G {
  H=0;
  K=3;
}

// The response message containing the greetings
message HelloReply {
  // The greeting message.
  string message = 1;
}
