#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
{{- if .Values.ingress.enabled }}
{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
apiVersion: networking.k8s.io/v1
{{- else if .Capabilities.APIVersions.Has "networking.k8s.io/v1beta1/Ingress" }}
apiVersion: networking.k8s.io/v1beta1
{{- else }}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ include "dolphinscheduler.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "dolphinscheduler.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
        - path: {{ .Values.ingress.path }}
          backend:
            {{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
            service:
              name: {{ include "dolphinscheduler.fullname" . }}-api
              port:
                name: api-port
            {{- else }}
            serviceName: {{ include "dolphinscheduler.fullname" . }}-api
            servicePort: api-port
            {{- end }}
          {{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
          pathType: Prefix
          {{- end }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    hosts:
      - {{ .Values.ingress.host }}
    secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
{{- end }}