@startuml
'https://plantuml.com/activity-diagram-beta

start
:外部模块调用安装方法;
:TaskPluginManager.installPlugin();
while(foreach factory : ServiceLoader.load(TaskChannelFactory.class))
:loadTaskChannel(factory);
:TaskPluginManager.taskChannelMap.put(taskChannelFactory.getName(), factory.create());
endwhile
:插件安装完成;
stop

@enduml
