#!/bin/bash

echo "------ dolphinscheduler start - build -------"
printenv

docker build --build-arg version=$version --build-arg tar_version=$tar_version  -t $DOCKER_REPO:$version .

echo "------ dolphinscheduler end   - build -------"
