<!-- pc meta config -->
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
<meta http-equiv="Cache-Control" content="no-siteapp" />
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-title" content="标题">
<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent"/>
<meta name="format-detection" content="telphone=no, email=no"/>
<meta name="screen-orientation" content="portrait">
<meta name="x5-orientation" content="portrait">
<meta name="theme-color" content="#4a8dee">
<meta name="msapplication-navbutton-color" content="#4a8dee">
<meta name="viewport" content="width=device-width,user-scalable=no,initial-scale=1,maximum-scale=1,minimum-scale=1">
<link rel="shortcut icon" href="${locals.PUBLIC_PATH}/images/favicon.ico"/>

<base href="/">
<link href="${locals.PUBLIC_PATH}/3rdcss/animate.css" rel="stylesheet">
<link href="${locals.PUBLIC_PATH}/3rdcss/bootstrap.min.css" rel="stylesheet">
<link href="${locals.PUBLIC_PATH}/3rdcss/codemirror.min.css" rel="stylesheet">
<link href="${locals.PUBLIC_PATH}/3rdcss/jsplumbtoolkit-defaults.min.css" rel="stylesheet">
<link href="${locals.PUBLIC_PATH}/3rdcss/mdn-like.min.css" rel="stylesheet">
<link href="${locals.PUBLIC_PATH}/3rdcss/normalize.min.css" rel="stylesheet">
<link href="${locals.PUBLIC_PATH}/3rdcss/reset.css" rel="stylesheet">
<link href="${locals.PUBLIC_PATH}/3rdcss/show-hint.min.css" rel="stylesheet">
<link href="${locals.PUBLIC_PATH}/3rdcss/vs.min.css" rel="stylesheet">


<script>
  let NODE_ENV = '${locals.NODE_ENV}'
</script>
