syntax = "proto3";

package org.apache.dolphinscheduler.task.grpc.proto;

option java_package = "org.apache.dolphinscheduler.plugin.task.grpc.generated";
option java_multiple_files = true;
option java_outer_classname = "TaskTesterProto";

service TaskTester {
  rpc TestOK (StringRequest) returns (StringReply) {}
  rpc TestUNIMPLEMENTED (StringRequest) returns (StringReply) {}
}

message StringRequest {
  string username = 1;
}

message StringReply {
  string message = 1;
}

message NoneRequest {

}

message NoneReply {

}
