#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
{{- if and (not .Values.postgresql.enabled) (not .Values.mysql.enabled) .Values.externalDatabase.ssl.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dolphinscheduler.fullname" . }}-db-ssl
  labels:
    app.kubernetes.io/name: {{ include "dolphinscheduler.fullname" . }}-db-ssl
    {{- include "dolphinscheduler.common.labels" . | nindent 4 }}
type: Opaque
data:
  ca-certificate: {{ .Files.Get .Values.externalDatabase.ssl.caCertificate | b64enc | quote }}
  {{- if .Values.externalDatabase.ssl.clientCertificate }}
  client-certificate: {{ .Files.Get .Values.externalDatabase.ssl.clientCertificate | b64enc | quote }}
  {{- end }}
  {{- if .Values.externalDatabase.ssl.clientKey }}
  client-key: {{ .Files.Get .Values.externalDatabase.ssl.clientKey | b64enc | quote }}
  {{- end }}
{{- end }}
