name: CI

on: [push, pull_request]

jobs:
  Compile-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: check
        run: mvn -U -B clean package assembly:assembly -Dmaven.test.skip=true
  License-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: check
        run: mvn -B apache-rat:check
